### ISSUE TITLE
Add Mario (from set 71360)

### ISSUE THREAD

**Issue by tthiery** [sharpbrick/powered-up#91]
Mario seems to be a simple Lego Wireless Protocol compatible Powered Up device.

I cannot support this integration since I lack hardware. If anyone is up interesting trying to add, I will assist and guide.

**Comment by tthiery** [comment]
See related https://github.com/nathankellenicki/node-poweredup/issues/103

**Comment by judavi** [comment]
Hi @tthiery !
I'll be happy to help if I get some guidance. I already have some code able to get the RGB camera colors and the accelerometer https://github.com/judavi/lego-mario

**Comment by tthiery** [comment]
Hi @judavi 

I am happy to give you the needed guidance! To onboard Mario,

1. the first thing would be an addition to the device types. I think that number you should already have.
2. Run the `poweredup device list` cli call to enumerate all internal devices/ports.
3. Dump the result here and have a conversation 🎉


I had a look at your code and I am not perfectly sure whether either your code is wrong (especially the switch instruction argument `data[0]`) or the fact that lego mario is using LWP 😁. As far as I remember, the first byte of the message is the length of the message and not the message type. Which coincidentally might work but is not correct. Third option: me having not read the core careful enough 😁

**Comment by tthiery** [comment]
@judavi i have eliminated the first step to simplify your onboarding. You would need to pull the code, compile it with .NET Core 3.1 and run the CLI project with the arguments `device list`. This operation will essentially you give you all the stuff the https://github.com/bricklife/LEGO-Mario-Reveng project has informally spread over a dozen tables in a tree style format. Afterward that, we can analyze which device the .NET library here needs and how to implement it.

**Comment by tthiery** [comment]
@judavi Got a bit excited and added already a pull request (#93). However, here I would need to stop. I would need the dump of the following commands (from the CLI project) to continue working without actual hardware ...

- `dotnet run -- device list`
- `dotnet run -- device dump-static-port -p 0`
- `dotnet run -- device dump-static-port -p 1`
- `dotnet run -- device dump-static-port -p 2`
- `dotnet run -- device dump-static-port -p 3`
- `dotnet run -- device dump-static-port -p 6`

The rest I would need to do (blindly w/o testing) the following work documented [here](docs/development/adding-new-device.md).

**Comment by judavi** [comment]
dotnet run -- device list
```
 .\SharpBrick.PoweredUp.Cli  -- device list
Scan Started. Please select the Hub (using a number keys or 'q' to terminate):
1: Mario (with address 106066114251875)
1
Selected Mario with key 1
Discover Ports. Receiving Messages ...
........................................................................................
Discover Ports Function: 87 / 87
Hub: 0
  Port: 0
    IOTypeId: 71
    HardwareRevision: 2.0.0.0
    SoftwareRevision: 0.0.0.1
    OutputCapability: False
    InputCapability: True
    LogicalCombinableCapability: True
    LogicalSynchronizableCapability: False
    ModeCombinations: [0000000000000011]
    UsedCombinationIndex: 0
    MultiUpdateEnabled: False
    ConfiguredModeDataSetIndex: []
    Mode: 0
      Name: RAW
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 100
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 100
      Symbol: cnt
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 3
      DatasetType: SByte
      TotalFigures: 3
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
    Mode: 1
      Name: GEST
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 100
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 100
      Symbol: cnt
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 2
      DatasetType: Int16
      TotalFigures: 3
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
  Port: 1
    IOTypeId: 73
    HardwareRevision: 2.0.0.0
    SoftwareRevision: 0.0.0.1
    OutputCapability: False
    InputCapability: True
    LogicalCombinableCapability: True
    LogicalSynchronizableCapability: False
    ModeCombinations: [0000000000000011]
    UsedCombinationIndex: 0
    MultiUpdateEnabled: False
    ConfiguredModeDataSetIndex: []
    Mode: 0
      Name: TAG
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 10
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 10
      Symbol: idx
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 2
      DatasetType: Int16
      TotalFigures: 3
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
    Mode: 1
      Name: RGB
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 10
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 10
      Symbol: raw
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 3
      DatasetType: SByte
      TotalFigures: 3
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
  Port: 2
    IOTypeId: 74
    HardwareRevision: 2.0.0.0
    SoftwareRevision: 0.0.0.1
    OutputCapability: False
    InputCapability: True
    LogicalCombinableCapability: False
    LogicalSynchronizableCapability: False
    ModeCombinations: []
    UsedCombinationIndex: 0
    MultiUpdateEnabled: False
    ConfiguredModeDataSetIndex: []
    Mode: 0
      Name: PANT
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 63
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 63
      Symbol: idx
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 1
      DatasetType: SByte
      TotalFigures: 3
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
  Port: 3
    IOTypeId: 70
    HardwareRevision: 2.0.0.0
    SoftwareRevision: 0.0.0.1
    OutputCapability: False
    InputCapability: True
    LogicalCombinableCapability: False
    LogicalSynchronizableCapability: False
    ModeCombinations: []
    UsedCombinationIndex: 0
    MultiUpdateEnabled: False
    ConfiguredModeDataSetIndex: []
    Mode: 0
      Name: CHAL
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 65535
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 65535
      Symbol: na
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 2
      DatasetType: Int16
      TotalFigures: 3
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
    Mode: 1
      Name: VERS
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 255
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 255
      Symbol: na
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 4
      DatasetType: Int32
      TotalFigures: 10
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
    Mode: 2
      Name: EVENTS
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 65535
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 65535
      Symbol: na
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 2
      DatasetType: Int16
      TotalFigures: 10
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
    Mode: 3
      Name: DEBUG
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 65535
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 65535
      Symbol: na
      InputSupportsNull: True
      InputSupportFunctionalMapping20: False
      InputAbsolute: False
      InputRelative: False
      InputDiscrete: True
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 4
      DatasetType: Int32
      TotalFigures: 10
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
  Port: 6
    IOTypeId: Voltage
    HardwareRevision: 0.0.0.1
    SoftwareRevision: 2.0.0.0
    OutputCapability: False
    InputCapability: True
    LogicalCombinableCapability: False
    LogicalSynchronizableCapability: False
    ModeCombinations: []
    UsedCombinationIndex: 0
    MultiUpdateEnabled: False
    ConfiguredModeDataSetIndex: []
    Mode: 0
      Name: VLT L
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 2705
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 3300
      Symbol: mV
      InputSupportsNull: False
      InputSupportFunctionalMapping20: False
      InputAbsolute: True
      InputRelative: False
      InputDiscrete: False
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 1
      DatasetType: Int16
      TotalFigures: 4
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
    Mode: 1
      Name: VLT S
      IsInput: True
      IsOutput: False
      RawMin: 0
      RawMax: 2705
      PctMin: 0
      PctMax: 100
      SIMin: 0
      SIMax: 3300
      Symbol: mV
      InputSupportsNull: False
      InputSupportFunctionalMapping20: False
      InputAbsolute: True
      InputRelative: False
      InputDiscrete: False
      OutputSupportsNull: False
      OutputSupportFunctionalMapping20: False
      OutputAbsolute: False
      OutputRelative: False
      OutputDiscrete: False
      NumberOfDatasets: 1
      DatasetType: Int16
      TotalFigures: 4
      Decimals: 0
      DeltaInterval: 0
      NotificationEnabled: False
```

dotnet run -- device dump-static-port -p 0

```
Scan Started. Please select the Hub (using a number keys or 'q' to terminate):
1: Mario (with address 106066114251875)
1
Selected Mario with key 1
Discover Port 0. Receiving Messages ...
.................
Discover Ports Function: 16 / 16
##################################################
0B-00-43-00-01-06-02-03-00-00-00
07-00-43-00-02-03-00
11-00-44-00-00-00-52-41-57-00-00-00-00-00-00-00-00
0E-00-44-00-00-01-00-00-00-00-00-00-C8-42
0E-00-44-00-00-02-00-00-00-00-00-00-C8-42
0E-00-44-00-00-03-00-00-00-00-00-00-C8-42
0A-00-44-00-00-04-63-6E-74-00
08-00-44-00-00-05-84-00
0A-00-44-00-00-80-03-00-03-00
11-00-44-00-01-00-47-45-53-54-00-00-00-00-00-00-00
0E-00-44-00-01-01-00-00-00-00-00-00-C8-42
0E-00-44-00-01-02-00-00-00-00-00-00-C8-42
0E-00-44-00-01-03-00-00-00-00-00-00-C8-42
0A-00-44-00-01-04-63-6E-74-00
08-00-44-00-01-05-84-00
0A-00-44-00-01-80-02-01-03-00
```

**Comment by judavi** [comment]
dotnet run -- device dump-static-port -p 1

```
 device dump-static-port -p 1
Scan Started. Please select the Hub (using a number keys or 'q' to terminate):
1: Mario (with address 106066114251875)
1
Selected Mario with key 1
Discover Port 1. Receiving Messages ...
.................
Discover Ports Function: 16 / 16
##################################################
0B-00-43-01-01-06-02-03-00-00-00
07-00-43-01-02-03-00
11-00-44-01-00-00-54-41-47-00-00-00-00-00-00-00-00
0E-00-44-01-00-01-00-00-00-00-00-00-20-41
0E-00-44-01-00-02-00-00-00-00-00-00-C8-42
0E-00-44-01-00-03-00-00-00-00-00-00-20-41
0A-00-44-01-00-04-69-64-78-00
08-00-44-01-00-05-84-00
0A-00-44-01-00-80-02-01-03-00
11-00-44-01-01-00-52-47-42-00-00-00-00-00-00-00-00
0E-00-44-01-01-01-00-00-00-00-00-00-20-41
0E-00-44-01-01-02-00-00-00-00-00-00-C8-42
0E-00-44-01-01-03-00-00-00-00-00-00-20-41
0A-00-44-01-01-04-72-61-77-00
08-00-44-01-01-05-84-00
0A-00-44-01-01-80-03-00-03-00
##################################################
```
dotnet run -- device dump-static-port -p 2

```
1: Mario (with address 106066114251875)
1
Selected Mario with key 1
Discover Port 2. Receiving Messages ...
...........
Discover Ports Function: 9 / 9
##################################################
0B-00-43-02-01-02-01-01-00-00-00
05-00-43-02-02
11-00-44-02-00-00-50-41-4E-54-00-00-00-00-00-00-00
0E-00-44-02-00-01-00-00-00-00-00-00-7C-42
0E-00-44-02-00-02-00-00-00-00-00-00-C8-42
0E-00-44-02-00-03-00-00-00-00-00-00-7C-42
0A-00-44-02-00-04-69-64-78-00
08-00-44-02-00-05-84-00
0A-00-44-02-00-80-01-00-03-00
##################################################
```

dotnet run -- device dump-static-port -p 3

```
Discover Port 3. Receiving Messages ...
...............................
Discover Ports Function: 30 / 30
##################################################
0B-00-43-03-01-02-04-0F-00-00-00
05-00-43-03-02
11-00-44-03-00-00-43-48-41-4C-00-00-00-00-00-00-00
0E-00-44-03-00-01-00-00-00-00-00-FF-7F-47
0E-00-44-03-00-02-00-00-00-00-00-00-C8-42
0E-00-44-03-00-03-00-00-00-00-00-FF-7F-47
0A-00-44-03-00-04-6E-61-00-00
08-00-44-03-00-05-84-00
0A-00-44-03-00-80-02-01-03-00
11-00-44-03-01-00-56-45-52-53-00-00-00-00-00-00-00
0E-00-44-03-01-01-00-00-00-00-00-00-7F-43
0E-00-44-03-01-02-00-00-00-00-00-00-C8-42
0E-00-44-03-01-03-00-00-00-00-00-00-7F-43
0A-00-44-03-01-04-6E-61-00-00
08-00-44-03-01-05-84-00
0A-00-44-03-01-80-04-02-0A-00
11-00-44-03-02-00-45-56-45-4E-54-53-00-00-00-00-00
0E-00-44-03-02-01-00-00-00-00-00-FF-7F-47
0E-00-44-03-02-02-00-00-00-00-00-00-C8-42
0E-00-44-03-02-03-00-00-00-00-00-FF-7F-47
0A-00-44-03-02-04-6E-61-00-00
08-00-44-03-02-05-84-00
0A-00-44-03-02-80-02-01-0A-00
11-00-44-03-03-00-44-45-42-55-47-00-00-00-00-00-00
0E-00-44-03-03-01-00-00-00-00-00-FF-7F-47
0E-00-44-03-03-02-00-00-00-00-00-00-C8-42
0E-00-44-03-03-03-00-00-00-00-00-FF-7F-47
0A-00-44-03-03-04-6E-61-00-00
08-00-44-03-03-05-84-00
0A-00-44-03-03-80-04-02-0A-00
##################################################
```

dotnet run -- device dump-static-port -p 6

```
Discover Port 6. Receiving Messages ...
.................
Discover Ports Function: 16 / 16
##################################################
0B-00-43-06-01-02-02-03-00-00-00
05-00-43-06-02
11-00-44-06-00-00-56-4C-54-20-4C-00-00-00-00-00-00
0E-00-44-06-00-01-00-00-00-00-00-10-29-45
0E-00-44-06-00-02-00-00-00-00-00-00-C8-42
0E-00-44-06-00-03-00-00-00-00-00-40-4E-45
0A-00-44-06-00-04-6D-56-00-00
08-00-44-06-00-05-10-00
0A-00-44-06-00-80-01-01-04-00
11-00-44-06-01-00-56-4C-54-20-53-00-00-00-00-00-00
0E-00-44-06-01-01-00-00-00-00-00-10-29-45
0E-00-44-06-01-02-00-00-00-00-00-00-C8-42
0E-00-44-06-01-03-00-00-00-00-00-40-4E-45
0A-00-44-06-01-04-6D-56-00-00
08-00-44-06-01-05-10-00
0A-00-44-06-01-80-01-01-04-00
##################################################
```

**Comment by tthiery** [comment]
Thanks. I will incorporate the stuff later today and write some scripts for testing. Awesome!

**Comment by judavi** [comment]
Great!! thanks @tthiery !! It took me a while to find a computer with Windows at home 😅

**Comment by tthiery** [comment]
Yeah, I guessed so. Seeing your repos and language choices. Btw, I have not heard of a go library for powered up devices. It is a simple protocol and easy to code once you get the patterns.

If you want to code in C# a bit, well, BLE energy adapters for macOS and Linux are missing.

**Comment by tthiery** [comment]
Hi @judavi 

Within the branch of the pull request #93 I started the implementation. I hope the following is completed

- MarioHubTagSensor (Barcode, ColorNo, RgbColor)
- MarioHubPants (Pants)

I added two examples to test them. For running the test do the following

0. Pull your repo to the latest version, checkout the branch of #93 and pull the latest commits.
1. Change the comments in `examples\SharpBrick.PoweredUp.Examples\Program.cs` the relevant example
2. Run `dotnet run` in the directory `examples\SharpBrick.PoweredUp.Examples`.
3. You have 20s to test the behavior. For the barcode example I modified the update interval to 100ms otherwise, i think the log is a bit to crazy. Change as needed in the example cs files.

Please perform the following tests

- Pants are recognized on, off and type of pants
- RGB Color is recognized
- ColorNo is recognized
- Tags as available are recognized

**Note**: Can you check the RGB color range. They are speced with 0..10 (raw) and 0..10 (SI). That invalidates basically the scaling ... i think the full byte range 0..255 is utilized, representing the full rgb spectrum (like done for the RgbLight). 

Would be nice if you can run the test case in the next days. I got request today for the TwoPortHub ... I would love to release a 3.1 version with both, Mario and TwoPortHub.

**Missing**
- Accelerator and Gesture: I am confused by the `cnt` unit ... i guess the accelerator is counting impacts not acceleration ... have to think about it.
- Voltage: device type 14 is bound to `Voltage`. Same for Mario, TechnicMedium and TwoPort Hubs. However, they have different voltages. I need to add the hub type to the filter for the static data. Need some design work and its too late for that 😀.
- Whole debugging thingy.

The testing for this will be a bit rougher.

**Comment by judavi** [comment]
For both scenarios (Go and C#) sounds really interesting!! 
For MacOs/Linux adapters could you point me what that means in terms of Windows? So I can get an idea?

Now! Let's talk about the specifics of the PR:

Steps: 
1. Changed the comment in Program.cs to Example.MarioPants()
2. Run in debug mode

Results:

![image](https://user-images.githubusercontent.com/1766933/95044621-c94e0180-06d7-11eb-924d-af0237174ae6.png)

![image](https://user-images.githubusercontent.com/1766933/95043835-d538c400-06d5-11eb-8c29-c3ab79c797b6.png)

In this case _service is coming back with a null value.

I'll try to debug but I just wanted to share what I saw in case you have an idea what it could be missing.

About RGB Color Range:
Yes I think the range is 0 to 255. As you notice my code is not working correctly for the movement but almost the colours part was correctly identifying the color range and I was using  https://github.com/judavi/lego-mario/blob/43d2727700c017ae721cceffb40b39c87ef7aee9/src/app.ts#L52

**Comment by tthiery** [comment]
That is a bit strange especially considering that you already run the CLI on the same computer which runs over the same code.

**Comment by judavi** [comment]
It is! because I'm able to run the same commands from yesterday without problems!!!

**Comment by tthiery** [comment]
Some more testing for you

- Fixed the Voltage situation

- Regards the accelerator: Can you dump me some values streams from e.g. your own library? this cnt is still confusing me like hell.
  - GEST has no unit in TechnicMediumHub. But it has four discrete values. That we could just test and ignore the unit if it fits otherwise.
  - Accelerometer measures Gravity ... which has a unit of mG in TechnicMediumHub.
  - Accelerometer and Gyro (IMHO) combines to TILT and Impact Sensors. Impact has a CNT unit in TechnicMediumHub .. however, without x,y,z differentiation for the cnt. Do you think you could test this with your solution ... and see how the sensor behaves. Whether it is really a accelerometer (detecting translation), gyro (detecting rotation) or tilt or impact (derived outcomes)

**Comment by judavi** [comment]
I'm still having issues connecting using the examples. Going deeper GetServiceAsync is returning null:

![image](https://user-images.githubusercontent.com/1766933/95174395-e6570300-07b1-11eb-8534-4fdcdf80dcc8.png)

**Comment by tthiery** [comment]
I have never experienced this issue. However, my tests run on my notebook with my hardware and my LEGO hardware.  I will not be able to reproduce this.

**Comment by judavi** [comment]
Sorry for the radio silence. I was trying to get a proper computer with Windows, my first test were executed on a thin client with an Intel Atom so I tht maybe was some hardware limitations. Now I have access to a proper PC so I'll run the tests during the weekend

**Comment by tthiery** [comment]
I am a bit worried about exactly that. I have neither had the chance to test the library much beyond my notebook. Every chip is a bit different and even with Microsoft unified drivers nowadays, quality of the integration and raw speed can most likely vary a lot. Keep us posted, and thanks for the update.

**Comment by judavi** [comment]
Just leaving here some thoughts...
In a quick test now it's getting stuck in a different part :

![image](https://user-images.githubusercontent.com/1766933/95497465-43ada880-099a-11eb-8671-c1058b50afbf.png)

**Comment by tthiery** [comment]
Yeah. Damn. That is not good.

I have seen this in my attempt to port this to WebAssembly/Blazor and using WebBluetooth. What happens here is one of the following:

1. good case: we/me have specified in the MarioHub too many expected devices. At the beginning of a Bluetooth connection, Lego Wireless Protocol hubs send HubAttachedIO messages for each internal and external device. That helps the library to understand what is connected at a given time. In this case we specified maybe too many!
2. Less bad case: Mario device itself does not follow this behavior (since it does not have external ports, maybe omitted. Check in the log for the HubAttachedIO messages (on the other hand then we would not be able to execute the command line like we did).
3. Very bad case: the Bluetooth setup is randomly not fast enough on the computer (like in my case via WebBluetooth) and the first HubAttachedIO message(s) are just swallowed. In that case the whole device discovery is a major roadblock for my library on devices with bad Bluetooth chips. Why I rely on this enumeration: the await speeds up the moment when I can first send a command (I await the finishing and not delay a period of time) AND like that I can react on device changes and do not need an app giving me the details.

I reported this issue to both LEGO and via StackOverflow it ended up in the WebBluetooth IG. I really hope it is 1 or 2.

**Comment by tthiery** [comment]
I think I seriously screwed up 😀 Good for us.

IMHO, the enum for the device IOTypes has bugs ;)

        MarioHubAccelerometer = 0x0040, // UNSPCED, https://github.com/bricklife/LEGO-Mario-Reveng (Lego Mario)
=> should be 0x0047
        MarioHubTagSensor = 0x041, // UNSPCED, https://github.com/bricklife/LEGO-Mario-Reveng (Lego Mario)
=> should be 0x0049
        MarioHubPants = 0x0042, // UNSPCED, https://github.com/bricklife/LEGO-Mario-Reveng (Lego Mario)
=> should be 0x004a
        MarioHubDebug = 0x0043, // UNSPCED, https://github.com/bricklife/LEGO-Mario-Reveng (Lego Mario)
=> should be 0x0046

**Comment by judavi** [comment]
Cool! Leet me try with those new values...

**Comment by judavi** [comment]
No way... we will need to wait until tomorrow ... this guy is tired 😵

![image](https://user-images.githubusercontent.com/1766933/95507033-b756b200-09a8-11eb-8328-0f1816bf5834.png)

**Comment by judavi** [comment]
I notice two particular things but I'm still not sure how to fix those:

![image](https://user-images.githubusercontent.com/1766933/95675180-21d83f80-0bad-11eb-996b-fcc20c1cdc62.png)

![image](https://user-images.githubusercontent.com/1766933/95675143-d6be2c80-0bac-11eb-99b7-8b77efdb0257.png)

How we can get the correct systemTypeId ?

And when is uncommented : 
![image](https://user-images.githubusercontent.com/1766933/95675172-0f5e0600-0bad-11eb-9800-2a249c24bdfe.png)

![image](https://user-images.githubusercontent.com/1766933/95675163-040ada80-0bad-11eb-8d47-cba454c4a473.png)

Probably as TechnicMediumHub with HardwareNetworkFamily in this case mario is not compatible with HardwareNetworkId.

**Comment by judavi** [comment]
Are we sure is this a 0x43 ?

![image](https://user-images.githubusercontent.com/1766933/95675955-cc9f2c80-0bb2-11eb-8707-5153797f3775.png)

**Comment by tthiery** [comment]
Well, the number is used in two enums. BLE Manufacturer data (which essentially instantiates the MarioHub class as a consequence) and as a SystemType property. These numbers match "usually". Try fixing the SystemType.

**Comment by tthiery** [comment]
Regards the network properties: branch on SystemType, exclude it for MarioHub. I will fix this more generic later.

**Comment by tthiery** [comment]
@judavi Hey, is Mario fit again?

**Comment by tthiery** [comment]
I added #121 which will help fixing the HardwareNetworkId issue. Will update this as soon as the other is in `master`

**Comment by tthiery** [comment]
Added known property types. This should be fixed now. The other one I need more input from you.

**Comment by tthiery** [comment]
So MarioHub. I have to apologize. This was unexpected not a "good first issue". The library is/was not ready for the plumper.

- [x] SystemType mismatch is bypassed by not querying the property
- [x] CombinedModePortValue retrieval (support for multi-value dataset in combined mode)
- [ ] SByte (speced by PortModeInfo) vs Byte (reality) usage in RGB color
- [ ] Scaling of percentage (and SI above boundaries of datatype)
- [ ] Color Coding of Blue is missing
